[project]
name = "comfyui-rife-film-only"
description = "A custom node set for Video Frame Interpolation in ComfyUI, containing only FILM and RIFE models"
version = "1.0.0"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/ThunderFun/ComfyUI-RIFE-FILM-Only"

[tool.comfy]
PublisherId = "ThunderFun"
DisplayName = "ComfyUI-RIFE-FILM-Only"
Icon = ""
